title: 'E-Geist'
baseurl: ""
url: "https://e-geist.github.io"

remote_theme: b2a3e8/jekyll-theme-console
theme: jekyll-theme-console
header_pages:
  - index.md
  - bio.md
  - projects_and_contributions.md

style: light # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true

footer: ''

google_analytics: UA-186970886-1
