title: 'E-Geist'
baseurl: ""
url: "https://www.eugengeist.dev"


header_pages:
  - index.md
  - bio.md
  - projects_and_contributions.md

style: light # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true

footer: ''

google_analytics: UA-186970886-1
